# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kguiaddons': '@latest'
    'frameworks/kidletime': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'libraries/plasma-wayland-protocols': '@latest'
    'plasma/kwayland': 'kf5'
    'third-party/wayland': '@latest'
    'third-party/wayland-protocols': '@latest'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
