# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kguiaddons': '@latest'
    'frameworks/kidletime': '@latest'
    'frameworks/kwayland': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'libraries/plasma-wayland-protocols': '@latest'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'
    'frameworks/kidletime': '@latest-kf6'
    'frameworks/kwayland': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'libraries/plasma-wayland-protocols': '@latest-kf6'
