# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kguiaddons': '@latest'
    'frameworks/kidletime': '@latest'
    'frameworks/kwayland': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'libraries/plasma-wayland-protocols': '@latest'
    'third-party/wayland': '@latest'
    'third-party/wayland-protocols': '@latest'
