# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kguiaddons': '@latest'
    'frameworks/kidletime': '@latest'
    'frameworks/kwayland': '@latest'
    'frameworks/kwindowsystem': '@latest'
